all: trie vector bloom DHashing
trie:  
	g++ -O2 diccTrie.cc -o diccTrie
vector:
	g++ -O2 diccSortedVector.cc -o diccSortedVector
bloom:
	g++ -O2 diccBloomFilter.cc -o diccBloomFilter
DHashing:
	g++ -O2 diccDHashing.cc -o diccDHashing

clean:
	rm diccTrie diccSortedVector diccBloomFilter diccDHashing
